#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

${PREFIX}black mangum tests --check
${PREFIX}mypy mangum --disallow-untyped-defs --ignore-missing-imports