#!/bin/sh -e


export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

if ! command -v "${PREFIX}twine" &>/dev/null ; then
    echo "Unable to find the 'twine' command."
    echo "Install from PyPI, using '${PREFIX}pip install twine'."
    exit 1
fi

find mangum -type f -name "*.py[co]" -delete
find mangum -type d -name __pycache__ -delete

${PREFIX}python setup.py sdist
${PREFIX}twine upload dist/*

echo "You probably want to also tag the version now:"
echo "git tag -a <version> -m 'version <version>'"
echo "git push --tags"

rm -r dist